spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/breezer
    username: breezer
    password: password
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true

logging:
  level:
    com:
      github:
        vahundos:
          breezer: debug