spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/breezer
    username: breezer
    password: password
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true

cors:
  allowed-origins: 'http://localhost:8000'
  allowed-methods: GET, POST
  allowed-headers: Accept, Content-Type, Authorization, X-Auth-Token

logging:
  level:
    com:
      github:
        vahundos:
          breezer: debug