spring:
  jpa:
    open-in-view: false
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
  servlet:
    multipart:
      max-file-size: 3MB

cors:
  allowed-origins: 'http://localhost:8000'
  allowed-methods: GET, POST
  allowed-headers: Accept, Content-Type, Authorization, X-Auth-Token