spring:
  datasource:
    url: jdbc:p6spy:postgresql://localhost:5432/breezer
    username: breezer
    password: password
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create

logging:
  level:
    com:
      github:
        vahundos:
          breezer: debug