spring:
  jpa:
    open-in-view: false
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always

cors:
  allowed-origins: 'http://localhost:8000'
  allowed-methods: GET, POST, DELETE, PUT
  allowed-headers: Accept, Content-Type, Authorization, X-Auth-Token
